id: A010E4DC1
base_file: f4488.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:04:09.001977
  last_modified_at: 2022-05-31 05:04:09.001993
